### ISSUE TITLE
add http request status code error checking

### ISSUE THREAD

**Issue by datwiz** [frankreno/sumologic-k8s-api#4]
Added checks for http requests to log and exit when an http return code other than "200" is returned.

Had an issue getting the job to work and added the return code checks to help debug the issue.
Turns out the error was due to an embedded line feed char in a secret, but the error checking helped to diagnose the issue.

**Comment by frankreno** [comment]
fixed by #5

**Comment by frankreno** [comment]
changes are now available in docker tag 0.0.3/latest
