### ISSUE TITLE
Fails to run on EKS

### ISSUE THREAD

**Issue by arafatmohammed** [frankreno/sumologic-k8s-api#6]
**Description:**
Running the rbac config on my EKS cluster and it fails with the following error:

**Steps to reproduce:**
$ kubectl create -f sumologic-k8s-api-cronjob-rbac.yaml

$ kubectl logs sumologic-k8s-api-1536183000-r8fcc sumologic-k8s-api
[sumologic-k8s-api-error.log](https://github.com/frankreno/sumologic-k8s-api/files/2354637/sumologic-k8s-api-error.log)

**Comment by frankreno** [comment]
Root cause:

1) All components in the YAML must run in the same namespace. 
2) No need to update k8s api url as the sidecar runs kubectl proxy
